//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyBudget.Www.App_DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public decimal Summa { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime Date { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ExpenditureCategory ExpenditureCategory { get; set; }
    }
}
