//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyBudget.Www.CBRService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.cbr.ru/", ConfigurationName="CBRService.DailyInfoSoap")]
    public interface DailyInfoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SaldoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SaldoXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/ROISfixXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ROISfixXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RuoniaXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode RuoniaXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OstatDepoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode OstatDepoXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OstatDepo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OstatDepo(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/ROISfix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ROISfix(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Ruonia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Ruonia(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/mrrf7D", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mrrf7D(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/mrrf7DXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode mrrf7DXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RepoDebtUSD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RepoDebtUSD(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RepoDebtUSDXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode RepoDebtUSDXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/mrrf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mrrf(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/mrrfXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode mrrfXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Saldo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Saldo(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NewsInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode NewsInfoXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OmodInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode OmodInfoXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/XVol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet XVol(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/XVolXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode XVolXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/MainInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode MainInfoXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/AllDataInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AllDataInfoXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NewsInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet NewsInfo(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SwapDynamicXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SwapDynamicXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SwapInfoSellUSDVolXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SwapInfoSellUSDVolXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SwapInfoSellUSDVol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SwapInfoSellUSDVol(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SwapInfoSellUSD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SwapInfoSellUSD(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SwapInfoSellUSDXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SwapInfoSellUSDXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BiCurBaseXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode BiCurBaseXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BiCurBase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BiCurBase(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BiCurBacketXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode BiCurBacketXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BiCurBacket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BiCurBacket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SwapDynamic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SwapDynamic(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SwapMonthTotal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SwapMonthTotal(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SwapMonthTotalXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SwapMonthTotalXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/MKR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MKR(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/MKRXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode MKRXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DV(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DVXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode DVXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Repo_debt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Repo_debt(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Repo_debtXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Repo_debtXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Coins_base", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Coins_base(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Coins_baseXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Coins_baseXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/FixingBase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FixingBase(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/FixingBaseXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode FixingBaseXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Overnight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Overnight(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OvernightXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode OvernightXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Bauction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Bauction(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BauctionXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode BauctionXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DepoDynamicXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode DepoDynamicXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DepoDynamic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DepoDynamic(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OstatDynamicXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode OstatDynamicXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OstatDynamic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OstatDynamic(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DragMetDynamicXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode DragMetDynamicXML(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DragMetDynamic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DragMetDynamic(System.DateTime fromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetLatestDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GetLatestDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetLatestDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLatestDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetLatestDateTimeSeld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GetLatestDateTimeSeld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetLatestDateSeld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLatestDateSeld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumValutesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode EnumValutesXML(bool Seld);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumValutes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EnumValutes(bool Seld);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetLatestReutersDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GetLatestReutersDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumReutersValutesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode EnumReutersValutesXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumReutersValutes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EnumReutersValutes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetReutersCursOnDateXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetReutersCursOnDateXML(System.DateTime On_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetReutersCursOnDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReutersCursOnDate(System.DateTime On_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetReutersCursDynamicXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetReutersCursDynamicXML(System.DateTime FromDate, System.DateTime ToDate, int NumCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetReutersCursDynamic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReutersCursDynamic(System.DateTime FromDate, System.DateTime ToDate, int NumCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetCursDynamicXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCursDynamicXML(System.DateTime FromDate, System.DateTime ToDate, string ValutaCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetCursDynamic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCursDynamic(System.DateTime FromDate, System.DateTime ToDate, string ValutaCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetCursOnDateXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCursOnDateXML(System.DateTime On_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetSeldCursOnDateXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetSeldCursOnDateXML(System.DateTime On_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetSeldCursOnDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSeldCursOnDate(System.DateTime On_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetCursOnDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCursOnDate(System.DateTime On_date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DailyInfoSoapChannel : FamilyBudget.Www.CBRService.DailyInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DailyInfoSoapClient : System.ServiceModel.ClientBase<FamilyBudget.Www.CBRService.DailyInfoSoap>, FamilyBudget.Www.CBRService.DailyInfoSoap {
        
        public DailyInfoSoapClient() {
        }
        
        public DailyInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DailyInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DailyInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DailyInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode SaldoXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.SaldoXML(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode ROISfixXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.ROISfixXML(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode RuoniaXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.RuoniaXML(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode OstatDepoXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.OstatDepoXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet OstatDepo(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.OstatDepo(fromDate, ToDate);
        }
        
        public System.Data.DataSet ROISfix(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.ROISfix(fromDate, ToDate);
        }
        
        public System.Data.DataSet Ruonia(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.Ruonia(fromDate, ToDate);
        }
        
        public System.Data.DataSet mrrf7D(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.mrrf7D(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode mrrf7DXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.mrrf7DXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet RepoDebtUSD(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.RepoDebtUSD(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode RepoDebtUSDXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.RepoDebtUSDXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet mrrf(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.mrrf(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode mrrfXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.mrrfXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet Saldo(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.Saldo(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode NewsInfoXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.NewsInfoXML(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode OmodInfoXML() {
            return base.Channel.OmodInfoXML();
        }
        
        public System.Data.DataSet XVol(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.XVol(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode XVolXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.XVolXML(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode MainInfoXML() {
            return base.Channel.MainInfoXML();
        }
        
        public System.Xml.XmlNode AllDataInfoXML() {
            return base.Channel.AllDataInfoXML();
        }
        
        public System.Data.DataSet NewsInfo(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.NewsInfo(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode SwapDynamicXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.SwapDynamicXML(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode SwapInfoSellUSDVolXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.SwapInfoSellUSDVolXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet SwapInfoSellUSDVol(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.SwapInfoSellUSDVol(fromDate, ToDate);
        }
        
        public System.Data.DataSet SwapInfoSellUSD(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.SwapInfoSellUSD(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode SwapInfoSellUSDXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.SwapInfoSellUSDXML(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode BiCurBaseXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.BiCurBaseXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet BiCurBase(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.BiCurBase(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode BiCurBacketXML() {
            return base.Channel.BiCurBacketXML();
        }
        
        public System.Data.DataSet BiCurBacket() {
            return base.Channel.BiCurBacket();
        }
        
        public System.Data.DataSet SwapDynamic(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.SwapDynamic(fromDate, ToDate);
        }
        
        public System.Data.DataSet SwapMonthTotal(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.SwapMonthTotal(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode SwapMonthTotalXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.SwapMonthTotalXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet MKR(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.MKR(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode MKRXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.MKRXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet DV(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.DV(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode DVXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.DVXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet Repo_debt(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.Repo_debt(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode Repo_debtXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.Repo_debtXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet Coins_base(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.Coins_base(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode Coins_baseXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.Coins_baseXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet FixingBase(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.FixingBase(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode FixingBaseXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.FixingBaseXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet Overnight(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.Overnight(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode OvernightXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.OvernightXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet Bauction(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.Bauction(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode BauctionXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.BauctionXML(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode DepoDynamicXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.DepoDynamicXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet DepoDynamic(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.DepoDynamic(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode OstatDynamicXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.OstatDynamicXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet OstatDynamic(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.OstatDynamic(fromDate, ToDate);
        }
        
        public System.Xml.XmlNode DragMetDynamicXML(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.DragMetDynamicXML(fromDate, ToDate);
        }
        
        public System.Data.DataSet DragMetDynamic(System.DateTime fromDate, System.DateTime ToDate) {
            return base.Channel.DragMetDynamic(fromDate, ToDate);
        }
        
        public System.DateTime GetLatestDateTime() {
            return base.Channel.GetLatestDateTime();
        }
        
        public string GetLatestDate() {
            return base.Channel.GetLatestDate();
        }
        
        public System.DateTime GetLatestDateTimeSeld() {
            return base.Channel.GetLatestDateTimeSeld();
        }
        
        public string GetLatestDateSeld() {
            return base.Channel.GetLatestDateSeld();
        }
        
        public System.Xml.XmlNode EnumValutesXML(bool Seld) {
            return base.Channel.EnumValutesXML(Seld);
        }
        
        public System.Data.DataSet EnumValutes(bool Seld) {
            return base.Channel.EnumValutes(Seld);
        }
        
        public System.DateTime GetLatestReutersDateTime() {
            return base.Channel.GetLatestReutersDateTime();
        }
        
        public System.Xml.XmlNode EnumReutersValutesXML() {
            return base.Channel.EnumReutersValutesXML();
        }
        
        public System.Data.DataSet EnumReutersValutes() {
            return base.Channel.EnumReutersValutes();
        }
        
        public System.Xml.XmlNode GetReutersCursOnDateXML(System.DateTime On_date) {
            return base.Channel.GetReutersCursOnDateXML(On_date);
        }
        
        public System.Data.DataSet GetReutersCursOnDate(System.DateTime On_date) {
            return base.Channel.GetReutersCursOnDate(On_date);
        }
        
        public System.Xml.XmlNode GetReutersCursDynamicXML(System.DateTime FromDate, System.DateTime ToDate, int NumCode) {
            return base.Channel.GetReutersCursDynamicXML(FromDate, ToDate, NumCode);
        }
        
        public System.Data.DataSet GetReutersCursDynamic(System.DateTime FromDate, System.DateTime ToDate, int NumCode) {
            return base.Channel.GetReutersCursDynamic(FromDate, ToDate, NumCode);
        }
        
        public System.Xml.XmlNode GetCursDynamicXML(System.DateTime FromDate, System.DateTime ToDate, string ValutaCode) {
            return base.Channel.GetCursDynamicXML(FromDate, ToDate, ValutaCode);
        }
        
        public System.Data.DataSet GetCursDynamic(System.DateTime FromDate, System.DateTime ToDate, string ValutaCode) {
            return base.Channel.GetCursDynamic(FromDate, ToDate, ValutaCode);
        }
        
        public System.Xml.XmlNode GetCursOnDateXML(System.DateTime On_date) {
            return base.Channel.GetCursOnDateXML(On_date);
        }
        
        public System.Xml.XmlNode GetSeldCursOnDateXML(System.DateTime On_date) {
            return base.Channel.GetSeldCursOnDateXML(On_date);
        }
        
        public System.Data.DataSet GetSeldCursOnDate(System.DateTime On_date) {
            return base.Channel.GetSeldCursOnDate(On_date);
        }
        
        public System.Data.DataSet GetCursOnDate(System.DateTime On_date) {
            return base.Channel.GetCursOnDate(On_date);
        }
    }
}
