//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyBudget.v3.App_DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentRulesInstruments
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public int PortfolioPercent { get; set; }
        public int PortfolioPercentDelta { get; set; }
    }
}
