//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyBudget.v3.App_DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentInstrument
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string DiagramBackgroundColor { get; set; }
        public string DiagramBackgroundHoverColor { get; set; }
        public string DiagramHoverBorderColor { get; set; }
        public Nullable<int> PortfolioPercent { get; set; }
        public Nullable<int> PortfolioPercentDelta { get; set; }
        public string ExternalAvatarIsinOverride { get; set; }
        public string ExternalPageTickerOverride { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> MarketID { get; set; }
    
        public virtual InvestmentInstrumentMarket InvestmentInstrumentMarket { get; set; }
        public virtual InvestmentInstrumentType InvestmentInstrumentType { get; set; }
    }
}
